- name: Ensure mandatory variables are defined
  fail:
    msg: "{{ item }} is undefined"
  when: item is undefined or item | length == 0
  with_items:
    - main_item.topicName
    - main_item.endpoint
    - main_item.env
    
- name: "Run prometheus query against {{ main_item.endpoint }} for {{ main_item.env }}"
  uri:
    url: "{{ main_item.endpoint }}/api/v1/query"
    method: POST
    body_format: form-urlencoded
    body:
      query: sum(kafka_minion_topic_subscribed_groups_count{topic="{{ main_item.topicName | quote }}", env="{{ main_item.env | quote }}"})
  register: prometheusResults

- name: Fail when there are active consumer groups
  fail:
    msg: "There are active consumer groups of {{ main_item.topicName }}"
  when: 
  - prometheusResults.json.status is defined
  - prometheusResults.json.data.result.0 is defined
  - prometheusResults.json.data.result.0.value.1 > 0
