--- 
- name: Install metricbeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.10.0-x86_64.rpm
    state: present

- name: create necessary folders
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
  loop:
    - /var/log/metricbeat-kafka
    - /var/lib/metricbeat-kafka

- name: Template out /etc/metricbeat/metricbeat-kafka.yml
  template:
    src: metricbeat-kafka.yml
    dest: /etc/metricbeat/metricbeat-kafka.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - restart metricbeat-kafka

- name: Template out metricbeat-kafka.service
  template:
    src: metricbeat-kafka.service
    dest: /etc/systemd/system/metricbeat-kafka.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart metricbeat-kafka

- meta: flush_handlers

- name: Start and enable metricbeat-kafka
  service:
    name: metricbeat-kafka
    state: started
    enabled: yes
