---
- name: create xfs
  filesystem:
    fstype: "{{ item.fstype | default('xfs') }}"
    dev: "{{ item.name }}"
    force: "{{ item.xfs_force | default('no') }}"
  with_items: "{{ main_item.devices }}"

- name: create mount point
  file:
    path: "{{ item.mount_point }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: directory
  with_items: "{{ main_item.devices }}"

- name: mount disk
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.name }}"
    fstype: "{{ item.fstype | default ('xfs') }}"
    state: "{{ item.state | default('mounted') }}"
    opts: "{{ item.opts | default('defaults') }}"
  with_items: "{{ main_item.devices }}"

- name: resize xfs
  filesystem:
    fstype: "{{ item.fstype | default('xfs') }}"
    dev: "{{ item.name }}"
    force: "{{ item.xfs_force | default('no') }}"
    resizefs: yes
  with_items: "{{ main_item.devices }}"
