---
- name: adding firewall service
  template: 
    src: firewall-service.xml.j2
    dest: "/etc/firewalld/services/{{ item.shortname }}.xml"
    owner: root
    group: root
  loop: "{{ firewall_services }}"

- name: pausing for services to become available
  pause:
    seconds: 10

- name: enabling service
  firewalld:
    service: "{{ item.shortname }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ firewall_services }}" 
