---
- name: REST Call
  ansible.builtin.uri:
    url: "{{ item.url }}"
    method: "{{ item.method | default('GET') }}"
    body: "{{ item.body | default('') }}"
    status_code: "{{ item.status_code | default('200') }}"
    body_format: "{{ item.body_format | default('json') }}"
    validate_certs: "{{ item.validate_certs | default('true') }}"
    return_content: "{{ item.return_content | default('false') }}"
  register: response_unauthenticated
  with_items: "{{ main_item.requests }}"
  when: 
    - item.src is not defined
    
- name: REST Call with with local file
  ansible.builtin.uri:
    url: "{{ item.url }}"
    method: "{{ item.method | default('GET') }}"
    src: "{{ item.src }}"
    remote_src: "{{ item.remote_src | default('false') }}"
    status_code: "{{ item.status_code | default('200') }}"
    body_format: "{{ item.body_format | default('json') }}"
    validate_certs: "{{ item.validate_certs | default('true') }}"
    return_content: "{{ item.return_content | default('false') }}"
  register: response_unauthenticated_file
  with_items: "{{ main_item.requests }}"
  when: 
    - item.src is defined
