---
- name: Ensure mandatory variables are defined
  fail:
    msg: "{{ item }} is undefined"
  when: item is undefined or item | length == 0
  with_items:
    - main_item.clientId
    - main_item.clientSecret
    - main_item.audience          # auth://chrobinson.com
    - main_item.grantType         # client_credential
    - main_item.oktaUrl           # https://chrobinson.oktapreview.com

- name: Get JWT from okta
  uri:
    url: "{{ main_item.oktaUrl }}/oauth2/ausvlbuzondNuiAlJ356/v1/token"
    method: POST
    body_format: form-urlencoded
    validate_certs: false
    body:
      client_id: "{{ main_item.clientId }}"
      client_secret: "{{ main_item.clientSecret }}"
      grant_type: "{{ main_item.grantType }}"
      audience: "{{ main_item.audience }}"
    status_code: 200
  register: token

- name: debug
  debug:
    msg: "{{ token.json }}"
    verbosity: 2
