- name: Ensure mandatory variables are defined
  fail:
    msg: "{{ item }} is undefined"
  when: item is undefined or item | length == 0
  with_items:
    - main_item.query
    - main_item.endpoint
    
- name: Run prometheus query
  uri:
    url: "{{ main_item.endpoint }}/api/v1/query"
    method: POST
    body_format: form-urlencoded
    body:
      query: "{{ main_item.query }}"
  register: prometheusResults
