---
- name: Ensure mandatory variables are defined
  fail:
    msg: "{{ item }} is undefined"
  when: item is undefined or item | length == 0
  with_items:
    - main_item.env
    - main_item.tech
    - main_item.file
    - main_item.brokers
    - main_item.topic
    - main_item.username
    - main_item.password
    - main_item.sasl_mechanism
    - main_item.security_protocol
    - main_item.compression_codec

- name: Install Redhat | Add yum repository
  yum_repository:
    name: TD_Agent_Bit
    baseurl: http://packages.fluentbit.io/centos/7/$basearch/
    gpgcheck: true
    gpgkey: http://packages.fluentbit.io/fluentbit.key
    description: Fluent bit repo
    enabled: true
    
- name: Install fluentbit package
  package:
    name: td-agent-bit
    state: present
    update_cache: true
  notify: Restart Fluentbit service

- name: Configure td-agent-bit
  template:
    src: dds-td-agent-bit.conf.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
    mode: 0644
  notify: Restart Fluentbit service
  
