- name: create group prometheus
  group:
    name: prometheus
    state: present

- name: create user prometheus
  user:
    name: prometheus
    state: present

- name: create temp dir for unpacking
  tempfile:
    state: directory
  register: tempdir

- name: fetch latest node-exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz"
    dest: "{{ tempdir.path }}/node-exporter.tar.gz"
  retries: 5
  delay: 5
  when: not ansible_check_mode

- name: unpack node-exporter.tar.gz
  unarchive:
    src: "{{ tempdir.path }}/node-exporter.tar.gz"
    dest: "{{ tempdir.path }}"
    remote_src: yes
  when: not ansible_check_mode
      
- name: "copy run-file to /usr/bin" 
  copy:
    src: "{{ tempdir.path }}/node_exporter-0.18.1.linux-amd64/node_exporter"
    dest: "{{ node_exporter_run_dir | default('/usr/bin/')}}"
    remote_src: yes
    mode: 0755
    owner: prometheus
    group: prometheus
  when: not ansible_check_mode

- name: template node-exporter.service
  template:
    src: templates/node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
  notify:
    - daemon_reload

- meta: flush_handlers

- name: enable and start service
  systemd:
    name: node-exporter
    state: started
    enabled: yes
    
- name: "Clean up {{ tempdir.path }}"
  file:
    path: "{{ tempdir.path }}"
    state: absent
  when: not ansible_check_mode
