---
- name: Ensure mandatory variables are defined
  fail:
    msg: "{{ item }} is undefined"
  when: item is undefined or item | length == 0
  with_items:
    - main_item.vg_name
    - main_item.lv_name
    - main_item.lv_size

- name: "check if vg {{ main_item.vg_name }} exists"
  shell: "vgs {{ main_item.vg_name }}"
  register: vg_exists
  changed_when: false
  check_mode: no

- name: "check if lv {{ main_item.lv_name }} exists"
  shell: "lvs {{ main_item.vg_name }} | grep {{ main_item.lv_name }} "
  register: lv_exists
  failed_when: false
  changed_when: false
  check_mode: no

- name: "lvcreate {{ main_item.vg_name }}/{{ main_item.lv_name }}"
  shell: "lvcreate -n {{ main_item.lv_name }} -L {{ main_item.lv_size }} {{ main_item.vg_name }}"
  changed_when: true
  check_mode: no
  when: vg_exists.rc == 0 and lv_exists.rc != 0
