---
- name: "ensure {{ item }} exists"
  shell: "lsblk | grep {{ item }}"
  register: lsblk_check
  failed_when: false
  changed_when: false
  check_mode: no

- name: "check if vg {{ main_item.vg_name }} already exists"
  shell: "vgs {{ main_item.vg_name }}"
  register: vg_exists
  failed_when: false
  changed_when: false
  check_mode: no

- name: "ensure that {{ item }} is not already in use"
  shell: "blkid | grep {{ item }}"
  register: dev_blkid
  failed_when: false
  changed_when: false
  check_mode: no
  when: vg_exists.rc == 0

- name: "check if {{ item }} is already in {{ item }}"
  shell: "pvs | grep {{ item }}"
  register: dev_pvs
  failed_when: false
  changed_when: false
  check_mode: no
  when: vg_exists.rc == 0

- name: "fail if {{ item }} is in use and not in {{ main_item.vg_name }}"
  fail:
    msg: "{{ item }} is already in use and not in {{ main_item.vg_name }}"
  when: dev_blkid == 0 and dev_pvs == 1

- name: "add {{ item }} to {{ main_item.vg_name }}"
  shell: vgextend {{ main_item.vg_name }} {{ item }}
  failed_when: false
  changed_when: false
  check_mode: no
  when: vg_exists.rc == 1 and dev_blkid.rc == 1 and dev_pvs.rc == 1
