- name: Reload sysctl
  shell: sysctl -p
  changed_when: true

- name: Reload unbound
  service: 
    name: unbound
    state: restarted

- name: reload systemctl
  shell: systemctl daemon-reload
  changed_when: true

- name: restart filebeat-kafka
  service:
    name: filebeat-kafka
    state: restarted

- name: restart metricbeat-kafka
  service:
    name: metricbeat-kafka
    state: restarted

- name: daemon_reload
  systemd:
    daemon_reload: yes
    
- name: Restart Fluentbit service
  service:
    name: td-agent-bit
    enabled: true
    state: restarted
  become: true

