filebeat.config:
  modules:
    path: /etc/filebeat/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: docker
  containers:
    ids: "*"
    path: {{ docker_dir.stdout }}/containers
  processors:
    - add_kubernetes_metadata:
        host: {{ ansible_hostname }}
        in_cluster: false
        kube_config: /etc/kubernetes/kubelet.conf
    - drop_event:
        when:
          equals:
            kubernetes.container.name: "filebeat"
  multiline:
    pattern: '^[[:space:]]'
    negate: false
    match: after
logging.level: info

# defaults to the emlog kafka cluster
output.kafka:
  enabled: true
  hosts: {{ filebeat_kafka_cluster }}
  topic: "{{ filebeat_kafka_topic }}"
  channel_buffer_size: 256
  ssl.enabled: false
  compression: gzip
  max_message_bytes: 1000000
